name: Action Bot Scheduler

on:
  push:
    branches:
      - master # Run on push to master

  schedule:
    - cron: "0 */12 * * *" # Run every 12 hours
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: yarn

      - run: node .
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          USER: ${{ secrets.USER }}

      - name: Commit new version
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_author: Bot <actions@github.com>
          commit_message: "[Bot] update README.md"

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master # The branch the action should deploy to.
          folder: . # The folder the action should deploy.
