name: Action Bot Scheduler

on:
  push:
    branches:
      - master # Run on push to master

  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: magic setup
        uses: actions/setup-node@v1
        with:
          node-version: 14.6.0

      - run: yarn

      - run: node .
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          USER: ${{ secrets.USER }}

      - name: Add to git repo
        run: |
          git add .
          git config --global user.name "abspen1"
          git config --global user.email "abspencer2097@gmail.com"
          git commit -m "âœ…   "
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
